variables:
  cypress_version: 12.5.1
  # E2E: the valid value is 'dev' or 'test'
  E2E: dev

cache: &global_cache
  - key: ${CI_JOB_NAME}_npm_cache
    paths:
      - .npm/
    when: always
    policy: pull-push

stages:
  - test

platformx-dev-job:
  image: 
    name: cypress/included:$cypress_version
    entrypoint: [""]
  stage: test
  cache: *global_cache
  before_script:
    - wget --no-check-certificate -nv https://github.com/cucumber/json-formatter/releases/latest/download/cucumber-json-formatter-linux-amd64 -O ./bin/cucumber-json-formatter
    - chmod +x ./bin/cucumber-json-formatter
    - npm ci --cache .npm --prefer-offline
  script:
    - echo "(${CI_JOB_NAME}) E2E env - ${E2E}";
    - echo "Cypress tags - ${cypress_TAGS}";
    - npm run run:dev:record
  artifacts:
    when: always
    paths:
      - results
      - downloads
    expire_in: "7 days"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $E2E == "dev"
      when: always
    - if: $CI_PIPELINE_SOURCE == "schedule" && $E2E == "dev"
      when: always
    - if: $CI_PIPELINE_SOURCE != "push" && $E2E == "dev"
      when: always
    - when: never
    
platformx-test-job:
  image: 
    name: cypress/included:$cypress_version
    entrypoint: [""]
  stage: test
  cache: *global_cache
  before_script:
    - wget --no-check-certificate -nv https://github.com/cucumber/json-formatter/releases/latest/download/cucumber-json-formatter-linux-amd64 -O ./bin/cucumber-json-formatter
    - chmod +x ./bin/cucumber-json-formatter
    - npm ci --cache .npm --prefer-offline
  script:
    - echo "(${CI_JOB_NAME}) E2E env - ${E2E}";
    - echo "Cypress tags - ${cypress_TAGS}";
    - npm run run:test
  artifacts:
    when: always
    paths:
      - results
      - downloads
    expire_in: "6 mos"
  rules:
    - if: $E2E == "test"
      when: always
    - when: never
